// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAid0RU91AAKu3JYeN0EgE42f3n01qjTiU',
    appId: '1:829357167561:web:d836256521182b26d78e18',
    messagingSenderId: '829357167561',
    projectId: 'appp-f8b9a',
    authDomain: 'appp-f8b9a.firebaseapp.com',
    storageBucket: 'appp-f8b9a.appspot.com',
    measurementId: 'G-WPSPGCGMFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-74jKkUlAaxOe9ORb3PzOb24l0WhKKk',
    appId: '1:829357167561:android:d3ed976fbf65c544d78e18',
    messagingSenderId: '829357167561',
    projectId: 'appp-f8b9a',
    storageBucket: 'appp-f8b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iCC5vnCl7PgaG298eWvQ3RpGvZXtoms',
    appId: '1:829357167561:ios:c4d81e71b5bd8af6d78e18',
    messagingSenderId: '829357167561',
    projectId: 'appp-f8b9a',
    storageBucket: 'appp-f8b9a.appspot.com',
    iosBundleId: 'com.example.asdas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iCC5vnCl7PgaG298eWvQ3RpGvZXtoms',
    appId: '1:829357167561:ios:c4d81e71b5bd8af6d78e18',
    messagingSenderId: '829357167561',
    projectId: 'appp-f8b9a',
    storageBucket: 'appp-f8b9a.appspot.com',
    iosBundleId: 'com.example.asdas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAid0RU91AAKu3JYeN0EgE42f3n01qjTiU',
    appId: '1:829357167561:web:adf517b367a31a7bd78e18',
    messagingSenderId: '829357167561',
    projectId: 'appp-f8b9a',
    authDomain: 'appp-f8b9a.firebaseapp.com',
    storageBucket: 'appp-f8b9a.appspot.com',
    measurementId: 'G-MVT3Y94SPD',
  );
}
